# Generated by Django 4.2.7 on 2026-02-08 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bank", "0002_bankmanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("FROZEN", "Frozen")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="approval_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="COMPLETED",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ManagerAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("FREEZE_ACCOUNT", "Freeze Account"),
                            ("UNFREEZE_ACCOUNT", "Unfreeze Account"),
                            ("APPROVE_TRANSACTION", "Approve Transaction"),
                            ("REJECT_TRANSACTION", "Reject Transaction"),
                            ("VIEW_USER", "View User Details"),
                            ("VIEW_ACCOUNT", "View Account Details"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="bank.bankmanager",
                    ),
                ),
                (
                    "target_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bank.account",
                    ),
                ),
                (
                    "target_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bank.transaction",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_actions_on",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager Action",
                "verbose_name_plural": "Manager Actions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
